apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  restartPolicy: Always
  imagePullSecrets:
    - name: naga
  containers:
    - name: httpd-container
      image: nagarajusatyala/private-repo:v2
      imagePullPolicy: Always
      ports:
        - containerPort: 8800
