apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  labels:
    app: httpd
spec:
  selector:
    app: httpd
  ports:
    - name: http
      port: 8080
      targetPort: 80
  type: LoadBalancer
