apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    environment: test
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer