variable "ami_id" {}
variable "inst_type" {}
variable "key_name" {}
variable "sg_ids" {}
variable "subnet_id" {}
variable "vpc_id" {}
variable "aws_region" {}
variable "lbsg_name" {}
variable "appsg_name" {}
variable "environment" {}
variable "solution" {}
