- hosts: loadbalancer
  become: yes
  tasks:
    - name: "Configure Load balancer"
      package:
        name: haproxy
    - template:
        dest: "/etc/haproxy/haproxy.cfg"
        src: "haproxy.cfg"
    - service:
        name: "haproxy"
        state: restarted
