apiVersion: v1
kind: Pod
metadata:
  name: myapp1
  labels:
    app: myapp
spec:
  restartPolicy: Always
  containers:
    - name: myapp-container
      image: coffee:v2
      imagePullPolicy: Never
      ports:
        - containerPort: 8080

